version: "3.9"

services:
  minio-api:
    image: ghcr.io/bookpanda/minio-api:e84a3db5b8034944c1a0fa7939f53d988c807440
    container_name: minio-api
    restart: unless-stopped
    networks:
      - proxy

    ports:
      - 3000:3000
    environment:
      - APP_PORT=3000
      - APP_ENV=production
      - APP_API_KEY=1234
      - APP_MAX_FILE_SIZE_MB=50
      - STORE_ENDPOINT=
      - STORE_ACCESS_KEY=
      - STORE_SECRET_KEY=
      - STORE_USE_SSL=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - minio-api
    networks:
      - proxy

    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - proxy
      
    ports:
      - 3001:3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234


networks:
  proxy:
    external: true

volumes:
  grafana-data: {}